# Generated by Django 5.0.4 on 2024-04-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_review_date_alter_review_book_alter_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
